title: HeMingxuan's Homepage
page-top-title: HeMingxuan
top-section-bg-text: Artificial Intelligence
home-subtitle: HeMingxuan&ensp;|&ensp;何铭轩
copyright-text: '&copy; He Mingxuan 2025-2026. All Rights Reserved.'
